### ISSUE TITLE
Can't run minimum example.

### ISSUE THREAD

**Issue by palsol** [digital-engineering/airbnb-scraper#13]
Hello! Great repo , but i can't figure out why basic example don't work. 
```scrapy crawl airbnb -a query="Colorado Springs, CO" -o colorado_springs.csv```

I got:
```HTTP status code is not handled or not allowed```

I  took api_key from ```api/v3/ExploreSearch```. I tried to change USER_AGENT to different values, but it didn't help.

**Comment by digitalengineering** [comment]
Hello! Thanks for using our project! Were you able to get this working eventually? I'm not sure exactly what the issue here was.
