### ISSUE TITLE
How to get AirBNB API key?

### ISSUE THREAD

**Issue by ashenkin** [digital-engineering/airbnb-scraper#16]
I'm not finding my API key with your suggested search string...  any recommendation for a new method to find this?  thanks...

**Comment by kevinle-1** [comment]
Ensure you are logged into AirBNB, 

1. Open developer tools
2. Open the networking tab
3. Filter by "key" (without quotes)
4. Refresh AirBNB page 
5. Notice the queries contain an API Key in the form `key=YOUR_API_KEY`

![image](https://user-images.githubusercontent.com/36955177/146193400-8dfe83bc-5912-464d-ae19-ed89d0a5e7ed.png)

**Comment by digitalengineering** [comment]
@kevinle-1 This is great! You're welcome to push a PR if you want to add this to the README, otherwise I will. Thank you.

**Comment by perryraskin** [comment]
Hey -- so I also found the key... but does it make any sense that a completely different Airbnb account has the same exact key? If they are the same, what is the significance of the key?

**Comment by digitalengineering** [comment]
When I initially wrote the script, I assumed the key would change frequently. Strangely though, it seems to always be the same. But, it seems still that it potentially *could* change one day. Also, I don't want to hard-code a "secret" into the repository.
