### ISSUE TITLE
How to scrap data directly with listing id, instead of searching?

### ISSUE THREAD

**Issue by dzqdudley** [digital-engineering/airbnb-scraper#18]
Hi, 

Your code is impressive, but now I have already get the listing ids, so there is no need to do the searching step.  I tried to modify the code but I failed. Can anyone provide some hints & suggestions? Thanks!

**Comment by digitalengineering** [comment]
Thanks! I don't think there is a way to do what you want currently. This project is based on scrapy, which is designed specifically for web scraping. It would probably be easier to create a new script. Once you get the page, you can look at `AirbnbSpider.parse()` in [deepbnb/spiders/airbnb.py](https://github.com/digital-engineering/airbnb-scraper/blob/b2ee4c0021576d0a2160d54a22abbe367e520275/deepbnb/spiders/airbnb.py#L60)
