### ISSUE TITLE
How can I get all the eligible search results?

### ISSUE THREAD

**Issue by dzqdudley** [digital-engineering/airbnb-scraper#19]
Hi,

I was running your code, but every time I could at most get 300 results back. I checked on airbnb, and found that if you searched manually, you would get at most 300 results as well. So maybe they are the same case. But is there any way that I can get all the results using this script? Thanks!

**Comment by digitalengineering** [comment]
That is correct. At most, the Airbnb backend system will only return 300 results at a time. The only way I know to circumvent this is to do multiple queries by price range, then combine the results.
