### ISSUE TITLE
Spider stops before finishing

### ISSUE THREAD

**Issue by LoganD19** [digital-engineering/airbnb-scraper#22]
This may be out of my beginner knowledge. But I only get a fraction of airbnb records before it stops. For example, I get on average 250-280 records. I did a query for "Boone, NC" and just "NC" and I got about the same amount of records. But for completely different listings. I know there are more records even for the city, because when I search on Airbnb for city I get 1000+ records for Boone, NC. Any idea on how this might be fixed? I can drop any files that I am working with here if needed. This is a great script and other than this issue, it works awesome.

**Comment by JovaniTarnowski** [comment]
Hello, @LoganD19 Can you send me the error that you are getting on the terminal? Maybe with more information I can help.

**Comment by LoganD19** [comment]
Sorry for the delay in reply. I will upload some info later this afternoon

**Comment by LoganD19** [comment]
I believe I am getting an "Error 5" Here's a time lapse screen recording I took of the two commands I ran, and here are the CSV outputs of both. Stupidly I closed the terminal and I don't believe there is a log file I can pull from. Thanks for your help!

[boone.csv](https://github.com/digital-engineering/airbnb-scraper/files/9424728/boone.csv)
[nc_all.csv](https://github.com/digital-engineering/airbnb-scraper/files/9424733/nc_all.csv)

(https://youtu.be/lRdwIfGhJJ0)

**Comment by digitalengineering** [comment]
Hi @LoganD19, thank you for the detailed comment!

Although Airbnb may indicate that there are **1000+** records for a given search, you will notice that it only provides 15 pages of results, each with 20 records per page. 20 x 15 = 300.

In other words, the maximum amount of results Airbnb will return for a given search is 300.

Without seeing your settings.py, it's not possible to know what other filter settings you might have in place, but 20-50 records could filtered out of the 300, giving you 250-280 records.
