### ISSUE TITLE
more than one spider issue and absence of prices

### ISSUE THREAD

**Issue by VB00** [digital-engineering/airbnb-scraper#23]
Hello, Thanks for the script!
I got two issues though:

1. I couldn't use advanced filters: "error: running 'scrapy crawl' with more than one spider is no longer supported". Windows 10 home, command prompt ; Madrid example was used.
2. Scraper collected everything with minimal query, except columns : price_rate, price_rate_type, total_price, monthly_price_factor, weekly_price_factor. Chrome Version 104.0.5112.82 (Official Build) (64-bit), File was csv, 233 rows.

**Comment by nvkodde** [comment]
I’m having same issue, none of the price fields are included in the output

**Comment by digitalengineering** [comment]
Hi there, I was not able to reproduce the "more than one spider" issue.

I have recently updated the project to fix the issues with price_rate, price_rate_type, and total_price. monthly_price_factor, weekly_price_factor are still not working.
