### ISSUE TITLE
Forbidden by robots.txt

### ISSUE THREAD

**Issue by essentialols** [digital-engineering/airbnb-scraper#8]
I get the following message and an output file of size 0.

[scrapy.downloadermiddlewares.robotstxt] DEBUG: Forbidden by robots.txt: <GET https://www.airbnb.com/api/v3/ExploreSearch?operationName=ExploreSearch&locale=en&currency=USD&variables=%7B%22request%22%3A%7B%22metadataOnly%22%3Afalse%2C%22version%22%3A%221.7.9%22%2C%22itemsPerGrid%22%3A20%2C%22tabId%22%3A%22home_tab%22%2C%22refinementPaths%22%3A%5B%22%2Fhomes%22%5D%2C%22source%22%3A%22search_blocks_selector_p1_flow%22%2C%22searchType%22%3A%22search_query%22%2C%22query%22%3A%22Oslo%2C+Norway%22%2C%22roomTypes%22%3A%5B%5D%2C%22cdnCacheSafe%22%3Afalse%2C%22simpleSearchTreatment%22%3A%22simple_search_only%22%2C%22treatmentFlags%22%3A%5B%22simple_search_1_1%22%2C%22flexible_dates_options_extend_one_three_seven_days%22%5D%2C%22screenSize%22%3A%22small%22%7D%7D&extensions=%7B%22persistedQuery%22%3A%7B%22version%22%3A1%2C%22sha256Hash%22%3A%2213aa9971e70fbf5ab888f2a851c765ea098d8ae68c81e1f4ce06e2046d91b6ea%22%7D%7D>
2021-02-19 15:45:35 [scrapy.core.engine] INFO: Closing spider (finished)
2021-02-19 15:45:35 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 1,
 'downloader/exception_type_count/scrapy.exceptions.IgnoreRequest': 1,
 'downloader/request_bytes': 230,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 5299,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 0.326508,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2021, 2, 19, 23, 45, 35, 938760),
 'log_count/DEBUG': 2,
 'log_count/INFO': 9,
 'memusage/max': 284704768,
 'memusage/startup': 284704768,
 'response_received_count': 1,
 'robotstxt/forbidden': 1,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2021, 2, 19, 23, 45, 35, 612252)}

**Comment by digitalengineering** [comment]
Hi @essentialols , I believe this is due to your robotstxt setting. Please review the scrapy documentation here: https://docs.scrapy.org/en/latest/topics/settings.html#robotstxt-obey

**Comment by essentialols** [comment]
Changing the robots.txt flag fixed it. Thanks!
